/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface HelpersScrollaway {}
}

declare global {


  interface HTMLHelpersScrollawayElement extends Components.HelpersScrollaway, HTMLStencilElement {}
  var HTMLHelpersScrollawayElement: {
    prototype: HTMLHelpersScrollawayElement;
    new (): HTMLHelpersScrollawayElement;
  };
  interface HTMLElementTagNameMap {
    'helpers-scrollaway': HTMLHelpersScrollawayElement;
  }
}

declare namespace LocalJSX {
  interface HelpersScrollaway extends JSXBase.HTMLAttributes<HTMLHelpersScrollawayElement> {}

  interface IntrinsicElements {
    'helpers-scrollaway': HelpersScrollaway;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


